image: node:6.11

stages:
  - install
  - build
  - test

before_script:
  - npm config set proxy http://ubuntuproxy:3142
  - npm config set https-proxy http://ubuntuproxy:3142
  - npm config set registry https://artifacts.uk.cambridgeconsultants.com/artifactory/api/npm/npmjs
  - npm install

cache:
  paths:
   - node_modules/
   - dist/

task_build:
  stage: build
  tags:
   - docker
  script: npm run build

task_test:
  stage: test
  tags:
   - docker
  script:
   - npm test