stages:
  - install
  - build
  - test

before_script:
  - call npm install

cache:
  paths:
   - node_modules/
   - dist/

task_build:
  stage: build
  tags:
   - shell
  script: call npm run build

task_test:
  stage: test
  tags:
   - shell
  script:
   - call npm test