image: node:6.11

stages:
  - install
  - build
  - test

before_script:
  - call npm config set registry https://artifacts.uk.cambridgeconsultants.com/artifactory/api/npm/npmjs
  - call npm install

cache:
  paths:
   - node_modules/
   - dist/

task_build:
  stage: build
  tags:
   - docker
  script: call npm run build

task_test:
  stage: test
  tags:
   - docker
  script:
   - call npm test