stages:
  - install
  - build
  - test

before_script:
  - npm install

cache:
  paths:
   - node_modules/

task_build:
  stage: build
  tags:
   - shell
  script: npm run build

task_test:
  stage: test
  tags:
   - shell
  script:
   - npm run build
   - npm test